name: latest_try_ct
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  sqflite: ^2.4.1
  dashed_circular_progress_bar: ^0.0.6
  path: ^1.9.0
  package_info_plus: ^5.0.1
  fl_chart: ^0.69.2
  week_number: ^1.1.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true